---
# based on https://github.com/mvdan/github-actions-golang
name: Deploy

on:
  #workflow_dispatch:
  #  inputs:
  #    version:
  #      description: "Semver version to deploy"
  #      required: true
  push:
    branches:
      - master
    paths:
      - "go.mod"
      - "go.sum"
      - ".github/**.yaml"
      - ".github/**.yml"
      - "api/**.go"
      - "cmd/**.go"
      - "internal/**.go"
      - "pkg/**.go"
      - "Dockerfile"
    paths-ignore:
      - docs/**
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: 🚀 Deploy
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: 📦 Checkout the repo
        uses: actions/checkout@v4
